In this notebook, we start by taking a look at our main dataset of skeletal malocclusion Class III in Caucasian patients, using simple statistics.

In [1]:
library(yaml)
library(dplyr)
library(psych)
library(tibble)
Sys.setlocale("LC_ALL", "en_US.UTF-8") # for the plus_minus character

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/C"

In [2]:
output_path <- "../outputs/data_exploration/"
# Create the output directory if it does not exist
if (!dir.exists(output_path)) {
  dir.create(output_path, recursive = TRUE)
}

In [3]:
# Load the configuration file
config <- yaml::yaml.load_file("../config.yml")

In [4]:
# Load datasets
df_cepha_measurements <- read.csv(paste0("../", config$dataset$cephalometric_measurements))
df_patient_info <- read.csv(paste0("../", config$dataset$patient_info))
df_coordinates <- read.csv(paste0("../", config$dataset$landmark_coordinates), check.names = FALSE)

In [5]:
dim(df_cepha_measurements)

[1] 655  55

In [6]:
dim(df_patient_info)

[1] 655   7

In [7]:
dim(df_coordinates)

[1] 655  25

# Population Size

In [8]:
nrow(df_patient_info)

[1] 655

# Population

In [9]:
table(df_patient_info$Population)

Iberian
    655

# Gender

In [10]:
table(df_patient_info$Gender)

  F   M
315 340

In [11]:
df_patient_info %>%
  group_by(Population, Gender) %>%
  summarize(count = n(), .groups = "drop")

  Population Gender count
1 Iberian    F      315
2 Iberian    M      340

# Cephalometric Measurements

In [12]:
df_summary_measurements <- describe(df_cepha_measurements %>% select(-Patient)) %>%
  as.data.frame() %>%
  round(2) %>%
  rownames_to_column(var = "Cephalometric_Variables") %>%
  select(Cephalometric_Variables, mean, sd) %>%
  mutate(mean_sd = paste(mean, " ± ", sd)) %>%
  select(Cephalometric_Variables, mean_sd)

df_summary_measurements %>% write.csv(file = paste0(output_path, "summary_statistics_measurements.csv"), row.names = TRUE)
df_summary_measurements

   Cephalometric_Variables             mean_sd
1  FH...SN..º.                         10.39  ±  3.55
2  SNA..º.                             79.49  ±  3.97
3  SNB..º.                             83.02  ±  4.66
4  ANB..º.                             -3.53  ±  3.58
5  SND..º.                             80.45  ±  4.44
6  Y.Axis..SGn.SN...º.                 66.56  ±  4.63
7  SN...GoGn..º.                       31.6  ±  7.02
8  Cranio.Mx.Base.SN.Palatal.Plane..º. 8.12  ±  3.84
9  Occ.Plane.to.SN..º.                 15.16  ±  5.23
10 Occ.Plane.to.FH..º.                 4.78  ±  5.03
11 Facial.Axis.Ricketts..NaBa.PtGn..º. 91.36  ±  5.36
12 FMA..MP.FH...º.                     23.91  ±  6.83
13 Lower.Face.Height..ANS.Xi.Pm..º.    44.62  ±  5.96
14 Facial.Angle..FH.NPo...º.           93.91  ±  4.3
15 N.A.Pg..º.                          -8.15  ±  6.88
16 Facial.Taper..º.                    62.17  ±  5.89
17 Gonial.Jaw.Angle..Ar.Go.Me...º.     127.7  ±  8.47
18 Upper.Gonial.Angle..Ar.Go.Na...º.   50.7  ±  4.59
19 Lower.Gonial.Angle..Na.Go.Me...º.   77  ±  6.71
20 Articular.Angle..º.                 142.06  ±  7.55
21 Saddle.Sella.Angle..SN.Ar...º.      124.54  ±  5.71
22 Superior.Angle.SN.AB..º.            88.22  ±  9.29
23 Rp.FH..º.                           76.21  ±  6.05
24 Anterior.Cranial.Base..SN...mm.     71.17  ±  15.49
25 Anterior.Face.Height..NaMe...mm.    127.41  ±  29.13
26 Upper.Face.Height..N.ANS...mm.      54.86  ±  12.01
27 Lower.Face.Height..ANS.Me...mm.     73.3  ±  18.15
28 Posterior.Cranial.Base..S.Ar...mm.  34.2  ±  7.98
29 Posterior.Face.Height..SGo...mm.    82.43  ±  19.33
30 Ramus.Height..Ar.Go...mm.           52.89  ±  13.53
31 Co.Go..mm.                          68.53  ±  18.32
32 Convexity..A.NPo...mm.              -4.3  ±  3.95
33 Maxillary.Skeletal..A.Na.Perp...mm. -0.08  ±  4.59
34 Midface.Length..Co.A...mm.          87.22  ±  19.54
35 Ar...A..mm.                         85.63  ±  18.67
36 Maxillary.length..ANS.PNS...mm.     55.13  ±  13.39
37 Pog...NB..mm.                       0.96  ±  3.14
38 Mand..Skeletal..Pg.Na.Perp...mm.    8.39  ±  10.7
39 Mandibular.Body.Length..Go.Gn..mm.  88.34  ±  20.94
40 Length.of.Mand.Base..Go.Pg..mm.     77.11  ±  17.64
41 Mandibular.length..Co.Gn..mm.       129.29  ±  30.94
42 Co.B1.Total.mand..mm.               126.72  ±  30.54
43 Ar...Gn..mm.                        121.93  ±  28.68
44 Basal.Width..mm.                    7.34  ±  2.44
45 Mx.Md.diff..Co.Gn...Co.A..mm.       42.07  ±  13.4
46 Wits.Appraisal..mm.                 -9.81  ±  6.85
47 P.A.Face.Height.S.Go.N.Me.....      64.85  ±  5.68
48 PFH.AFH....                         53.73  ±  5.56
49 S.Ar.Ar.Go....                      65.66  ±  10.34
50 UFH..N.ANS..N.ANS.ANS.Me......      42.93  ±  2.55
51 LFH.TFH..ANS.Me.N.Me.....           57.14  ±  2.59
52 Face.Ht.Ratio..N.ANS.ANS.Me.....    0.75  ±  0.09
53 SN.GoMe....                         97.59  ±  9.06
54 ANS.PNS.Me.Go....                   0.75  ±  0.09

# Selected Landmark Coordinates

In [13]:
colnames(df_coordinates %>% select(-Patient))

 [1] "X_Sella"                    "Y_Sella"
 [3] "X_Basion"                   "Y_Basion"
 [5] "X_PNS"                      "Y_PNS"
 [7] "X_A Point"                  "Y_A Point"
 [9] "X_B Point"                  "Y_B Point"
[11] "X_Pogonion"                 "Y_Pogonion"
[13] "X_Menton"                   "Y_Menton"
[15] "X_Gonion"                   "Y_Gonion"
[17] "X_Ramus Point"              "Y_Ramus Point"
[19] "X_Distal Aspect of Condyle" "Y_Distal Aspect of Condyle"
[21] "X_Condylion"                "Y_Condylion"
[23] "X_Nasion"                   "Y_Nasion"

In [14]:
landmarks_labels <- unique(gsub("^X_|^Y_", "", colnames(df_coordinates %>% select(-Patient))))
landmarks_labels

 [1] "Sella"                    "Basion"
 [3] "PNS"                      "A Point"
 [5] "B Point"                  "Pogonion"
 [7] "Menton"                   "Gonion"
 [9] "Ramus Point"              "Distal Aspect of Condyle"
[11] "Condylion"                "Nasion"

In [15]:
length(landmarks_labels)

[1] 12

# Treatmemt

In [16]:
table(df_patient_info$Treatment)

no-surgery    surgery
       292        363